### ISSUE TITLE
Always alert 'Unable to get the video URL.'

### ISSUE THREAD

**Issue by greedynamic** [alik604/stream.sfu.ca-media-downloader#1]
Hello @alik604,

Thanks for this useful script and I used it for many of my classes already. But it doesn't work recently. I don't know if sfu changed the stream security or sth. This script doesn't work for any of my class now. 

Let me know if you know how to fix.
Thanks

**Comment by alik604** [comment]
Hey, Im glad to hear it helped you. 
I have not used it in a few semesters and not had any issues the last I tried to use it
Are you around the Burnaby campus after 5:30 today? We can take a look and maybe its a quick fix. My discord is alik604#5388

**Comment by greedynamic** [comment]
Hey! So glad to hear back from you so quickly! I'm not going to campus today and my courses this term are all in Surrey. I added you on discord. I'm void new. yeah let's chat on discord!

**Comment by alik604** [comment]
Fixed via #2 :)
